pipeline {
    agent any
    environment {
        DOCKER_HUB_REGISTRY = 'beibei860429/springboot-backend'
        GITHUB_CREDENTIALS_ID = 'github-token'
        DOCKER_CREDENTIALS_ID = 'dockerhub-pwd'
    }
    stages {
        stage('Fetch Code') {
            steps {
                git branch: 'main', credentialsId: "${GITHUB_CREDENTIALS_ID}", url: 'https://github.com/beibei860429/pokeshop-fullstack.git'
            }
        }
        stage('Maven Build') {
            steps {
                // 👈 核心修改：用 dir 進入後端資料夾再跑 Maven
                dir('springboot-project') {
                    script {
                        docker.image('maven:3.8-openjdk-17').inside('-v /root/.m2:/root/.m2') {
                            sh 'mvn clean package -DskipTests'
                        }
                    }
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                // 👈 核心修改：用 dir 進入後端資料夾，才能抓到裡面的 Dockerfile
                dir('springboot-project') {
                    script {
                        env.IMAGE_TAG = "v_${env.BUILD_NUMBER}"
                        docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                            def customImage = docker.build("${DOCKER_HUB_REGISTRY}:${env.IMAGE_TAG}")
                            customImage.push()
                            customImage.push('latest')
                        }
                    }
                }
            }
        }
    }
}